"""Codec tests. The wire format is a commitment: once a payment carries these bytes
on chain, the decoder has to keep reading them forever. So the golden vectors here are
byte exact and hand written, not generated by the encoder they are testing."""

from __future__ import annotations

import datetime as dt

import pytest

from sanad.iso20022 import (
    FLAG_DOCUMENT_HASH,
    FLAG_FX,
    FLAG_STRUCTURED,
    CodecError,
    FxLeg,
    PaymentInstruction,
    StructuredRemittance,
    decode,
    describe,
    document_hash,
    encode,
    memo_id,
)

SUPPLIER = PaymentInstruction(end_to_end_id="INV-AE-1001", purpose="SUPP")


def test_minimal_instruction_is_byte_exact() -> None:
    # magic, version, no flags, purpose, then two length prefixed ASCII fields.
    expected = b"SNAD" + b"\x01" + b"\x00" + b"SUPP" + b"\x0b" + b"INV-AE-1001" + b"\x00"
    assert encode(SUPPLIER) == expected
    assert len(expected) == 23


def test_prefix_is_readable_as_ascii_in_an_explorer() -> None:
    raw = encode(SUPPLIER)
    assert raw[:4] == b"SNAD"
    assert raw[6:10] == b"SUPP"
    # The end to end id sits in the clear, so raw hex on Arcscan is still legible.
    assert b"INV-AE-1001" in raw


def test_decode_of_a_hand_written_vector() -> None:
    raw = b"SNAD\x01\x00SALA\x07PAY-001\x04A-42"
    instruction = decode(raw)
    assert instruction.end_to_end_id == "PAY-001"
    assert instruction.purpose == "SALA"
    assert instruction.creditor_reference == "A-42"
    assert instruction.purpose_description == "Salary payment"
    assert instruction.remittance is None


def test_round_trip_with_every_optional_section() -> None:
    full = PaymentInstruction(
        end_to_end_id="INV-AE-1001",
        purpose="TRAD",
        creditor_reference="SUP-042",
        remittance=StructuredRemittance(
            invoice_number="INV-AE-1001",
            invoice_date=dt.date(2026, 7, 31),
            invoice_amount_minor=1_250_000,
        ),
        document_sha256=document_hash(b"<Document><pain.001/></Document>"),
        fx=FxLeg(source_currency="AED", source_amount_minor=459_000, rate_scaled_1e12=272_294_000_000),
    )
    raw = encode(full)
    assert raw[5] == FLAG_STRUCTURED | FLAG_DOCUMENT_HASH | FLAG_FX
    assert decode(raw) == full


def test_a_structured_supplier_payment_stays_small() -> None:
    instruction = PaymentInstruction(
        end_to_end_id="INV-AE-1001",
        purpose="SUPP",
        creditor_reference="SUP-042",
        remittance=StructuredRemittance(
            invoice_number="INV-AE-1001",
            invoice_date=dt.date(2026, 7, 31),
            invoice_amount_minor=1_250_000,
        ),
    )
    # Gas is paid per byte of calldata and event data, so the budget is real.
    assert len(encode(instruction)) <= 64


def test_memo_id_matches_the_transaction_already_on_arc() -> None:
    # From tx 0xe8a80745f54098fe3d1ad14f81077f9ada81e1223aca61c21b5937d6234c02ef on
    # Arc testnet, whose Memo event carries this indexed memoId for INV-2026-0001.
    assert (
        memo_id("INV-2026-0001").hex()
        == "905373307d597fac2ae5d3a92554b3c2274054f9380f99f337e993c8503d82fe"
    )
    assert len(memo_id("anything")) == 32
    assert memo_id("a") != memo_id("b")


@pytest.mark.parametrize(
    ("raw", "message"),
    [
        (b"NOPE\x01\x00SUPP\x01A\x00", "magic"),
        (b"SNAD\x02\x00SUPP\x01A\x00", "unsupported version"),
        (b"SNAD\x01\x80SUPP\x01A\x00", "unknown flags"),
        (b"SNAD\x01\x00SUPP\x0bINV", "truncated"),
        (b"SNAD\x01\x00SUPP\x01A\x00trailing", "trailing bytes"),
    ],
)
def test_decode_refuses_malformed_bytes(raw: bytes, message: str) -> None:
    with pytest.raises(CodecError, match=message):
        decode(raw)


def test_encode_refuses_an_instruction_it_cannot_represent() -> None:
    with pytest.raises(CodecError, match="not a supported code"):
        PaymentInstruction(end_to_end_id="X", purpose="NOPE")
    with pytest.raises(CodecError, match="Max35Text"):
        PaymentInstruction(end_to_end_id="I" * 36, purpose="SUPP")
    with pytest.raises(CodecError, match="required"):
        PaymentInstruction(end_to_end_id="", purpose="SUPP")
    with pytest.raises(CodecError, match="32 bytes"):
        PaymentInstruction(end_to_end_id="X", purpose="SUPP", document_sha256=b"short")
    with pytest.raises(CodecError, match="alpha-3"):
        FxLeg(source_currency="AEDX", source_amount_minor=1, rate_scaled_1e12=1)


def test_describe_reads_like_a_receipt_line() -> None:
    line = describe(
        PaymentInstruction(
            end_to_end_id="INV-AE-1001",
            purpose="SUPP",
            creditor_reference="SUP-042",
            remittance=StructuredRemittance(
                invoice_number="INV-AE-1001",
                invoice_date=dt.date(2026, 7, 31),
                invoice_amount_minor=1_250_000,
            ),
        )
    )
    assert "INV-AE-1001" in line
    assert "Supplier payment" in line
    assert "1.25" in line
    assert "2026-07-31" in line
